version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: capstone-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - capstone-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: capstone-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - capstone-network

volumes:
  db_data:

networks:
  capstone-network:
    driver: bridge

