// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Community struct {
	ID          uuid.UUID        `json:"id"`
	RtNumber    int32            `json:"rt_number"`
	RwNumber    int32            `json:"rw_number"`
	Subdistrict string           `json:"subdistrict"`
	District    string           `json:"district"`
	City        string           `json:"city"`
	Province    string           `json:"province"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID        `json:"id"`
	Fullname    string           `json:"fullname"`
	Email       pgtype.Text      `json:"email"`
	Phone       pgtype.Text      `json:"phone"`
	Address     pgtype.Text      `json:"address"`
	Role        string           `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	CommunityID uuid.UUID        `json:"community_id"`
}
