// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findUserByID = `-- name: FindUserByID :one
select
  u.id, u.fullname, u.role, u.is_confirmed, u.created_at, u.updated_at, u.community_id,
  c.id, c.rt_number, c.rw_number, c.subdistrict, c.district, c.city, c.province, c.is_confirmed, c.created_at, c.updated_at
from users u
inner join communities c on c.id = u.community_id
where u.id = $1
`

type FindUserByIDRow struct {
	ID            uuid.UUID        `json:"id"`
	Fullname      string           `json:"fullname"`
	Role          string           `json:"role"`
	IsConfirmed   bool             `json:"is_confirmed"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CommunityID   uuid.UUID        `json:"community_id"`
	ID_2          uuid.UUID        `json:"id_2"`
	RtNumber      int32            `json:"rt_number"`
	RwNumber      int32            `json:"rw_number"`
	Subdistrict   string           `json:"subdistrict"`
	District      string           `json:"district"`
	City          string           `json:"city"`
	Province      string           `json:"province"`
	IsConfirmed_2 bool             `json:"is_confirmed_2"`
	CreatedAt_2   pgtype.Timestamp `json:"created_at_2"`
	UpdatedAt_2   pgtype.Timestamp `json:"updated_at_2"`
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Role,
		&i.IsConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommunityID,
		&i.ID_2,
		&i.RtNumber,
		&i.RwNumber,
		&i.Subdistrict,
		&i.District,
		&i.City,
		&i.Province,
		&i.IsConfirmed_2,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const insertCommunity = `-- name: InsertCommunity :one
insert into communities (
    id,
    rt_number,
    rw_number,
    subdistrict,
    district,
    city,
    province,
    is_confirmed
) values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id
`

type InsertCommunityParams struct {
	ID          uuid.UUID `json:"id"`
	RtNumber    int32     `json:"rt_number"`
	RwNumber    int32     `json:"rw_number"`
	Subdistrict string    `json:"subdistrict"`
	District    string    `json:"district"`
	City        string    `json:"city"`
	Province    string    `json:"province"`
	IsConfirmed bool      `json:"is_confirmed"`
}

func (q *Queries) InsertCommunity(ctx context.Context, arg InsertCommunityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCommunity,
		arg.ID,
		arg.RtNumber,
		arg.RwNumber,
		arg.Subdistrict,
		arg.District,
		arg.City,
		arg.Province,
		arg.IsConfirmed,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
insert into users (
    id,
    community_id,
    fullname,
    role,
    is_confirmed
) values ($1, $2, $3, $4, $5)
returning id
`

type InsertUserParams struct {
	ID          uuid.UUID `json:"id"`
	CommunityID uuid.UUID `json:"community_id"`
	Fullname    string    `json:"fullname"`
	Role        string    `json:"role"`
	IsConfirmed bool      `json:"is_confirmed"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.CommunityID,
		arg.Fullname,
		arg.Role,
		arg.IsConfirmed,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCommunityStatus = `-- name: UpdateCommunityStatus :exec
update communities
set is_confirmed = $1
where id = (
  select u.community_id
  from users u
  where u.id = $2
)
`

type UpdateCommunityStatusParams struct {
	IsConfirmed bool      `json:"is_confirmed"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCommunityStatus(ctx context.Context, arg UpdateCommunityStatusParams) error {
	_, err := q.db.Exec(ctx, updateCommunityStatus, arg.IsConfirmed, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
update users
set is_confirmed = $1
where id = $2
`

type UpdateUserStatusParams struct {
	IsConfirmed bool      `json:"is_confirmed"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.IsConfirmed, arg.ID)
	return err
}
